name: dcss-minimal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - pandas
  - leidenalg
  - seaborn
  - matplotlib
  - scikit-learn
  - spacy
  - pymc3
  - pip
  - numpy
  - beautifulsoup4
  - networkx
  - python-louvain
  - pyyaml
  - graphviz
  - pip:
    - dcss
